# Site settings
title: varname1
description: > # this means to ignore newlines until "baseurl:"
  I'm a dev
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://varname1.github.io" # the base hostname & protocol for your site
remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag